# Generated by Django 4.0.4 on 2023-09-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_gift', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_link',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='game_sub_id',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
