# Generated by Django 4.0.4 on 2023-09-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_gift', '0003_alter_code_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
