# Generated by Django 4.0.4 on 2023-09-11 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('send_gift', '0004_game_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='send_gift.account'),
            preserve_default=False,
        ),
    ]
