# Generated by Django 4.0.4 on 2023-09-11 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_gift', '0005_code_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='username',
            new_name='link',
        ),
    ]
