# Generated by Django 4.0.4 on 2023-09-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_gift', '0006_rename_username_code_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='course',
            field=models.FloatField(default=0),
        ),
    ]
